// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// softmax_jacobian_multiply
arma::vec softmax_jacobian_multiply(arma::vec gradient, arma::vec z);
RcppExport SEXP _sibships_softmax_jacobian_multiply(SEXP gradientSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gradient(gradientSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(softmax_jacobian_multiply(gradient, z));
    return rcpp_result_gen;
END_RCPP
}
// landscape_model_loglik
double landscape_model_loglik(arma::vec par, arma::mat landscape_distance_to_traps, arma::mat colony_counts_at_traps, arma::vec floral_cover_at_traps, arma::vec landscape_age);
RcppExport SEXP _sibships_landscape_model_loglik(SEXP parSEXP, SEXP landscape_distance_to_trapsSEXP, SEXP colony_counts_at_trapsSEXP, SEXP floral_cover_at_trapsSEXP, SEXP landscape_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type landscape_distance_to_traps(landscape_distance_to_trapsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type colony_counts_at_traps(colony_counts_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type floral_cover_at_traps(floral_cover_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type landscape_age(landscape_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_model_loglik(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age));
    return rcpp_result_gen;
END_RCPP
}
// landscape_model_gradient
arma::vec landscape_model_gradient(arma::vec par, arma::mat landscape_distance_to_traps, arma::mat colony_counts_at_traps, arma::vec floral_cover_at_traps, arma::vec landscape_age);
RcppExport SEXP _sibships_landscape_model_gradient(SEXP parSEXP, SEXP landscape_distance_to_trapsSEXP, SEXP colony_counts_at_trapsSEXP, SEXP floral_cover_at_trapsSEXP, SEXP landscape_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type landscape_distance_to_traps(landscape_distance_to_trapsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type colony_counts_at_traps(colony_counts_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type floral_cover_at_traps(floral_cover_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type landscape_age(landscape_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_model_gradient(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age));
    return rcpp_result_gen;
END_RCPP
}
// landscape_model_fitted
Rcpp::List landscape_model_fitted(arma::vec par, arma::mat landscape_distance_to_traps, arma::mat colony_counts_at_traps, arma::vec floral_cover_at_traps, arma::vec landscape_age);
RcppExport SEXP _sibships_landscape_model_fitted(SEXP parSEXP, SEXP landscape_distance_to_trapsSEXP, SEXP colony_counts_at_trapsSEXP, SEXP floral_cover_at_trapsSEXP, SEXP landscape_ageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type landscape_distance_to_traps(landscape_distance_to_trapsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type colony_counts_at_traps(colony_counts_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type floral_cover_at_traps(floral_cover_at_trapsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type landscape_age(landscape_ageSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_model_fitted(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sibships_softmax_jacobian_multiply", (DL_FUNC) &_sibships_softmax_jacobian_multiply, 2},
    {"_sibships_landscape_model_loglik", (DL_FUNC) &_sibships_landscape_model_loglik, 5},
    {"_sibships_landscape_model_gradient", (DL_FUNC) &_sibships_landscape_model_gradient, 5},
    {"_sibships_landscape_model_fitted", (DL_FUNC) &_sibships_landscape_model_fitted, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sibships(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
