# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

softmax_jacobian_multiply <- function(gradient, z) {
    .Call(`_sibships_softmax_jacobian_multiply`, gradient, z)
}

landscape_model_loglik <- function(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age) {
    .Call(`_sibships_landscape_model_loglik`, par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age)
}

landscape_model_gradient <- function(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age) {
    .Call(`_sibships_landscape_model_gradient`, par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age)
}

landscape_model_fitted <- function(par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age) {
    .Call(`_sibships_landscape_model_fitted`, par, landscape_distance_to_traps, colony_counts_at_traps, floral_cover_at_traps, landscape_age)
}

